server {
    listen 8080;
    server_name _;

    location = /login {
        error_page 418 = @mediwaste_login;
        if ($request_method = GET) { return 418; }

        proxy_pass http://api-gateway:8080;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location @mediwaste_login {
        root /usr/share/nginx/html;
        try_files /login.html =404;
        add_header Cache-Control "no-store";
    }

    location / {
        proxy_pass http://api-gateway:8080;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
    }
}
